name: Publish to AWS S3

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'

env:
  PROJECT_NAME: WebAppPrac
  DOTNET_VERSION: 6.0.x
  AWS_REGION: ap-northeast-2

jobs:
  linux_build:
  
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Setup .NET
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: ${{ env.DOTNET_VERSION }}

        - name: Restore dependencies
          run: dotnet restore

        - name: Build
          run: dotnet build --configuration Release
          
        - name: configure aws credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            role-to-assume: arn:aws:iam::165291449861:role/github-action-s3
            role-session-name: user-role
            aws-region: ${{ env.AWS_REGION }}

        - name: Deploy 
          run: |
            aws s3 cp \
              --recursive \
              /home/runner/work/WebAppPrac/WebAppPrac/WebAppPrac/bin/Release/net6.0/ s3://vms-s3-devops/dotnet/linux
       
  window_build:
  
      runs-on: windows-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Setup .NET
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: ${{ env.DOTNET_VERSION }}

        - name: Restore dependencies
          run: dotnet restore

        - name: Build
          run: dotnet build --configuration Release
          
        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            role-to-assume: arn:aws:iam::165291449861:role/github-action-s3
            role-session-name: user-role
            aws-region: ${{ env.AWS_REGION }}
          
        - name: Deploy 
          run: 
            aws s3 cp 
              --recursive 
              D:\a\WebAppPrac\WebAppPrac\WebAppPrac\bin\Release\net6.0\ s3://vms-s3-devops/dotnet/window

  trigger:  
    needs: linux_build
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Send Trigger
        run: |
          curl -X POST https://api.github.com/repos/seongjihye1994/vue-githubactions/dispatches \
          -H 'Accept: application/vnd.github.v3+json' \
          -u ${{ secrets.PAT }} \
          -d '{ "event_type": "demo_event" }'

