name: Publish to GitHub Packages

on:
  push:
    branches:
      - main

env:
  PROJECT_NAME: WebAppPrac
  PACKAGE_NAME: WebAppPrac
  DOTNET_VERSION: 6.0.x

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

      - name: Packaging
        run: dotnet pack --configuration Release

      - name: Publish
        run: aws s3 cp \
            --recursive \
            --region ap-northeast-2 \
            dist s3://WebAppPrac

