name: Build and Deploy ASP.NET Package
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.100-preview.7.21379.14'
    - name: Restore Dependencies
      run: dotnet restore
    - name: Build Project
      run: dotnet build --configuration Release
    - name: Publish Package
      run: dotnet pack --configuration Release --include-symbols
    - name: Set up NuGet
      run: |
        echo "machine api.nuget.org" >> ~/.netrc
        echo "  login ${{ secrets.NUGET_API_KEY }}" >> ~/.netrc
    - name: Push Package to GitHub Packages
      run: dotnet nuget push **/*.nupkg --source https://nuget.pkg.github.com/OWNER/index.json
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: 1
