name: Publish to GitHub Packages

on:
  push:
    branches:
      - main

env:
  PROJECT_NAME: WebAppPrac
  PACKAGE_NAME: WebAppPrac
  DOTNET_VERSION: 6.0.x

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

      - name: Packaging
        run: dotnet pack --configuration Release

      - name: Deploy 
        env:
          AWS_ACCESS_KEY_ID: AKIASM7BDLYCWCMRCLPK
          AWS_SECRET_ACCESS_KEY: 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
          AWS_DEFAULT_REGION: ap-northeast-2
        run: |
          aws s3 sync ./build s3://vms-s3-devops
